// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qnorkgosfpyuzmgoenvd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFub3JrZ29zZnB5dXptZ29lbnZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTQ5NTgsImV4cCI6MjA2NTQ3MDk1OH0.XNChKuZa3WMn_oGuUkq9QQviqvFj42yagPd_FN8I-Cs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);